apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simplilearn-phpinfo-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simplilearn-phpinfo
  template:
    metadata:
      labels:
        app: simplilearn-phpinfo
    spec:
      containers:
      - name: simplilearn-phpinfo-container
        image: academiaonline/simplilearn-phpinfo:latest
        command:
          - "php"
        args: 
          - "-f"
          - "index.php"
          - "-S"
          - "0.0.0.0:8080"
      - name: mysql-container
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: '1234'
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql
        emptyDir: {}
